### PR TITLE
Further docs clarifications

### PR DESCRIPTION
**Pull request by Half-Shot**

### CODE REVIEW

**Comment by Half-Shot** [comment]
@HarHarLinks let me know how this reads

**Review by HarHarLinks — CHANGES_REQUESTED** [review]
This addresses my issues with the docs (yet my suggestion to expand GitLab capabilities stands) provided the markdown list now works, except for a small oversight.

**Comment by HarHarLinks** [comment]
maybe you can also incorporate #152 in this PR

**Review by HarHarLinks — APPROVED** [review]

**Comment by Half-Shot** [comment]
>yet my suggestion to expand GitLab capabilities stands

I'm going to leave that issue open as a reminder to have split out secrets work.

**Pull request merged**
